name: First workflow
on: [push]

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: ech a string
              run: echo "Hello World"
            - name: "Multiple Command"
              run : |
                node -v
                npm -v
    parallel-job-macos:
        runs-on: macos-latest
        steps:
            - name: view SW version
              run: sw_vers
    dependent-job:
        runs-on: windows-latest
        needs: run-shell-commands
        steps:
            - name: echo a astring
              run: Write-Output "Windows String"
            
            - name: Error Step
              run: doesnotexits
